### ISSUE TITLE
Proceeding with the Client whose previous contacts were done by different user has some issues.

### ISSUE THREAD

**Issue by dodosi** [OpenSRP/opensrp-client-core#924] opened 2024-02-05 14:28 UTC
When the user tries to create contact 2 of the client whose information was fed by another user, it becomes difficult as it is not possible to view the Client's profile and previously fed information by a different user.

The issues are as follows when you try to work with information fed by other users.
1. When you click to see the profile, the app crashes.
2. When you click to start specific contact, previous fed data does not appear as it is expected
**App's Screenshot**
![image](https://github.com/opensrp/opensrp-client-core/assets/8068177/75d21156-401f-41d6-8b51-c19867a299d7)
**The error logs**
![image](https://github.com/opensrp/opensrp-client-core/assets/8068177/ce1164ad-16ba-4cea-8f82-11b625ff2a33)
**Code**
![image](https://github.com/opensrp/opensrp-client-core/assets/8068177/651d0cda-d4a5-4ad7-ba9b-a914e0dd6f24)

@dubdabasoduba @Naima-Bashir

**Comment by hilpitome** [comment] 2024-02-07 07:39
@dodosi We do not have the Keycloak client secret and id. Would you please send it to me via email.

**Comment by hilpitome** [comment] 2024-02-07 07:47
Also note that for security purposes we have new recommendations on the Keycloak clients used for authentication. This Applies to both OpenSRP v1 and OpenSRP v2.
1. (IMPORTANT) please disable `Service Account Roles` incase it is enabled for the OAuth Client your production application uses.
2. There should be 3` separate OAuth clients` corresponding to the separate OpenSRP clients (`Android, Web, Data ETLs`)
**OpenSRP Keycloak OAuth Client Setup Guideline**
1. Android client - enable  `Direct Access Grant `only - To fetch a token you will not need the client secret
2. Web client - enable `Client Authentication` and enable `Standard flow`  (Enable implicit flow only for local dev testing - can be configured for stage and maybe preview but NOT production)
3. Data/Analytics client -  enable `Client Authentication `and enable `Service Account Roles` cc @dodosi

**Comment by hilpitome** [comment] 2024-02-08 07:48
It looks like the population of the facts map is being done on the main thread. If I am correct, I will be moving the related functions into a background thread.

**Comment by Naima-Bashir** [comment] 2024-02-28 10:10
This has been resolved and confirmed by 1000 Hills solutions. Closing this cc @hilpitome

**Closed as completed by Naima-Bashir** 2024-02-28 10:10 UTC
